version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: sensor_db
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/sensordb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
